CC = gcc

CFLAGS = -I../cd/include -I../iup/include

LIBS = -L../cd/lib/mingw3 -L../iup/lib/mingw3 \
       -lcdiup -lcd -liup \
       -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lole32 -lcomctl32

OBJS = simple.o iupmain.o

all: simple.exe

simple.o:  simple.c simple.h
	$(CC) -o $@ -c simple.c $(CFLAGS)

iupmain.o:  iupmain.c simple.h
	$(CC) -o $@ -c iupmain.c $(CFLAGS)

simple.exe: $(OBJS)
	$(CC) -o $@ $(OBJS) $(LIBS)
