/* Automatically generated by Iup ledc 2.6         */

#include <stdlib.h>
#include <stdarg.h>
#include <iup.h>

static Ihandle* named[    172 ];

static Ihandle* decl( char* name, Ihandle* elem, char* first, ...)
{
  char *attr, *val;
  va_list arg;
  va_start (arg, first);
  attr = first;
  while (attr)
  {
    val = va_arg(arg,char*);
    IupSetAttribute( elem, attr, val );
    attr = va_arg(arg,char*);
  }
  va_end (arg);
  if(name) IupSetHandle( name, elem );
  return elem;
}

static void image_imgLine (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgLine", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", NULL );
}

static void image_imgClip (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgClip", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", NULL );
}

static void image_imgImage (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 0, 0, 0, 0,
     0, 0, 0, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 2, 2, 2, 1, 3, 2, 2, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 2, 2, 2, 2, 1, 2, 2, 1, 3, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 2, 2, 2, 1, 1, 2, 2, 1, 3, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 1, 3, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 2, 1, 3, 1, 2, 1, 3, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 2, 2, 1, 3, 2, 1, 3, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 1, 3, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 3, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 3, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgImage", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", 
    "3", "153 153 153", NULL );
}

static void image_imgImageRGB (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgImageRGB", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "255 0 0", 
    "2", "0 255 0", 
    "3", "0 0 255", NULL );
}

static void image_imgBox (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgBox", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}

static void image_imgRect (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgRect", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}

static void image_imgSector (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgSector", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}

static void image_imgChord (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
     0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgChord", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}

static void image_imgArc (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 2, 2, 2, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgArc", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}

static void image_imgText (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 0, 0,
     0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0,
     0, 0, 2, 2, 0, 0, 0, 0, 2, 2, 0, 1, 1, 1, 1, 1, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgText", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "255 255 255", 
    "2", "0 0 0", NULL );
}

static void image_imgPoly (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
     0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
     0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgPoly", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", NULL );
}

static void image_imgMark (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
     0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgMark", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", NULL );
}

static void image_imgPixel (void)
{
  unsigned char map[] = {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0,
     0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -1 };

  decl( "imgPixel", IupImage( 18, 18, map ), 
    "0", "BGCOLOR", 
    "1", "0 0 0", 
    "2", "255 255 255", NULL );
}


void cdtest_loadled (void)
{
  image_imgLine ();
  image_imgClip ();
  image_imgImage ();
  image_imgImageRGB ();
  image_imgBox ();
  image_imgRect ();
  image_imgSector ();
  image_imgChord ();
  image_imgArc ();
  image_imgText ();
  image_imgPoly ();
  image_imgMark ();
  image_imgPixel ();
  named[0] = decl( "mnOpen", IupMenu(
    IupItem( "MF...", "cmdPlayMF" ),
    named[1] = decl( "itPlayCGM", IupItem( "CGM...", "cmdPlayCGM" ), 
      "ACTIVE", "NO", NULL ),
    named[2] = decl( "itPlayEMF", IupItem( "EMF...", "cmdPlayEMF" ), 
      "ACTIVE", "NO", NULL ),
    named[3] = decl( "itPlayWMF", IupItem( "WMF...", "cmdPlayWMF" ), 
      "ACTIVE", "NO", NULL ),
  NULL), NULL );
  named[4] = decl( "mnSave", IupMenu(
    IupItem( "MF...", "cmdMF" ),
    named[5] = decl( "itPDF", IupItem( "PDF...", "cmdPDF" ), 
      "ACTIVE", "NO", NULL ),
    named[6] = decl( "itPS", IupItem( "PS...", "cmdPS" ), 
      "ACTIVE", "NO", NULL ),
    named[7] = decl( "itEPS", IupItem( "EPS...", "cmdEPS" ), 
      "ACTIVE", "NO", NULL ),
    named[8] = decl( "itCGMt", IupItem( "CGMt...", "cmdCGMt" ), 
      "ACTIVE", "NO", NULL ),
    named[9] = decl( "itCGMb", IupItem( "CGMb...", "cmdCGMb" ), 
      "ACTIVE", "NO", NULL ),
    named[10] = decl( "itDGN", IupItem( "DGN...", "cmdDGN" ), 
      "ACTIVE", "NO", NULL ),
    named[11] = decl( "itDXF", IupItem( "DXF...", "cmdDXF" ), 
      "ACTIVE", "NO", NULL ),
    named[12] = decl( "itEMF", IupItem( "EMF...", "cmdEMF" ), 
      "ACTIVE", "NO", NULL ),
    named[13] = decl( "itWMF", IupItem( "WMF...", "cmdWMF" ), 
      "ACTIVE", "NO", NULL ),
  NULL), NULL );
  named[14] = decl( "mnFile", IupMenu(
    decl( NULL, IupSubmenu( "Open",
      named[0] /* mnOpen */
    ), 
      "KEY", "K_O", NULL ),
    IupSeparator(),
    decl( NULL, IupSubmenu( "Save",
      named[4] /* mnSave */
    ), 
      "KEY", "K_S", NULL ),
    IupSeparator(),
    named[15] = decl( "itPrint", IupItem( "Print...", "cmdPrint" ), 
      "KEY", "K_P", NULL ),
    IupSeparator(),
    decl( NULL, IupItem( "Exit", "cmdFileExit" ), 
      "KEY", "K_x", NULL ),
  NULL), NULL );
  named[16] = decl( "mnEdit", IupMenu(
    named[17] = decl( "itEditUndo", IupItem( "Undo", "cmdEditUndo" ), NULL ),
    IupSeparator(),
    named[18] = decl( "itClipBoard", IupItem( "Copy as EMF/WMF", "cmdClipBoard" ), 
      "ACTIVE", "NO", NULL ),
    named[19] = decl( "itClipBoardBitmap", IupItem( "Copy as Bitmap", "cmdClipBoardBitmap" ), 
      "ACTIVE", "NO", NULL ),
    named[20] = decl( "itClipBoardMetafile", IupItem( "Copy as CD Metafile", "cmdClipBoardMetafile" ), 
      "ACTIVE", "NO", NULL ),
    named[21] = decl( "itClipBoardPaste", IupItem( "Paste", "cmdClipBoardPaste" ), 
      "ACTIVE", "NO", NULL ),
    IupSeparator(),
    IupItem( "Clear", "cmdEditClear" ),
    IupSeparator(),
    IupItem( "Options...", "cmdOptions" ),
  NULL), NULL );
  named[22] = decl( "mnPrimitives", IupMenu(
    IupItem( "Pixel...", "cmdPixel" ),
    IupItem( "Mark...", "cmdMark" ),
    IupItem( "Line...", "cmdLine" ),
    IupItem( "Polygon...", "cmdPoly" ),
    IupItem( "Rect...", "cmdRect" ),
    IupItem( "Box...", "cmdBox" ),
    IupItem( "Arc...", "cmdArc" ),
    IupItem( "Sector...", "cmdSector" ),
    IupItem( "Chord...", "cmdChord" ),
    IupItem( "Text...", "cmdText" ),
    IupSeparator(),
    IupItem( "Server Image...", "cmdImage" ),
    IupItem( "RGB Image...", "cmdImageRGB" ),
  NULL), NULL );
  named[23] = decl( "mnDraw", IupMenu(
    decl( NULL, IupSubmenu( "Primitives",
      named[22] /* mnPrimitives */
    ), 
      "KEY", "K_P", NULL ),
    IupSeparator(),
    IupItem( "Clipping...", "cmdClip" ),
    IupItem( "Attributes...", "cmdAttributes" ),
    IupSeparator(),
    named[24] = decl( "itWDCanvas", IupItem( "Show WD Canvas", "cmdWDCanvas" ), NULL ),
    named[25] = decl( "itPICCanvas", IupItem( "Show Picture Canvas", "cmdPICCanvas" ), NULL ),
  NULL), 
    "ISMENU", "YES", NULL );
  named[26] = decl( "mnHelp", IupMenu(
    IupItem( "About...", "cmdHelpAbout" ),
  NULL), NULL );
  named[27] = decl( "mnMain", IupMenu(
    decl( NULL, IupSubmenu( "File",
      named[14] /* mnFile */
    ), 
      "KEY", "K_mF", NULL ),
    decl( NULL, IupSubmenu( "Edit",
      named[16] /* mnEdit */
    ), 
      "KEY", "K_mE", NULL ),
    decl( NULL, IupSubmenu( "Draw",
      named[23] /* mnDraw */
    ), 
      "KEY", "K_mD", NULL ),
    decl( NULL, IupSubmenu( "Help",
      named[26] /* mnHelp */
    ), 
      "KEY", "K_mH", NULL ),
  NULL), NULL );
  named[28] = decl( "lbStatusLine", IupLabel( "Esta eh a barra de status do CDTest." ), 
    "EXPAND", "HORIZONTAL", NULL );
  named[29] = decl( "btLine", IupButton( "", "cmdLine" ), 
    "IMAGE", "imgLine", 
    "TIP", "Line", NULL );
  named[30] = decl( "btBox", IupButton( "", "cmdBox" ), 
    "IMAGE", "imgBox", 
    "TIP", "Box", NULL );
  named[31] = decl( "btRect", IupButton( "", "cmdRect" ), 
    "IMAGE", "imgRect", 
    "TIP", "Rect", NULL );
  named[32] = decl( "btArc", IupButton( "", "cmdArc" ), 
    "IMAGE", "imgArc", 
    "TIP", "Arc", NULL );
  named[33] = decl( "btSector", IupButton( "", "cmdSector" ), 
    "IMAGE", "imgSector", 
    "TIP", "Sector", NULL );
  named[34] = decl( "btChord", IupButton( "", "cmdChord" ), 
    "IMAGE", "imgChord", 
    "TIP", "Chord", NULL );
  named[35] = decl( "btPixel", IupButton( "", "cmdPixel" ), 
    "IMAGE", "imgPixel", 
    "TIP", "Pixel", NULL );
  named[36] = decl( "btMark", IupButton( "", "cmdMark" ), 
    "IMAGE", "imgMark", 
    "TIP", "Mark", NULL );
  named[37] = decl( "btText", IupButton( "", "cmdText" ), 
    "IMAGE", "imgText", 
    "TIP", "Text", NULL );
  named[38] = decl( "btPoly", IupButton( "", "cmdPoly" ), 
    "IMAGE", "imgPoly", 
    "TIP", "Polygon", NULL );
  named[39] = decl( "btImageRGB", IupButton( "", "cmdImageRGB" ), 
    "IMAGE", "imgImageRGB", 
    "TIP", "RGB Image", NULL );
  named[40] = decl( "btImage", IupButton( "", "cmdImage" ), 
    "IMAGE", "imgImage", 
    "TIP", "Server Image", NULL );
  named[41] = decl( "btClip", IupButton( "", "cmdClip" ), 
    "IMAGE", "imgClip", 
    "TIP", "Clipping Area", NULL );
  named[42] = decl( "btCurPrim", IupButton( "", "cmdShowDialog" ), 
    "IMAGE", "imgLine", 
    "TIP", "Show primitive dialog", NULL );
  named[43] = decl( "lbMousePos", IupLabel( "(    ,    )" ), 
    "SIZE", "90", NULL );
  named[44] = decl( "PrimBar", IupVbox(
    named[42] /* btCurPrim */,
    decl( NULL, IupFill(), 
      "SIZE", "20", NULL ),
    named[35] /* btPixel */,
    named[36] /* btMark */,
    named[29] /* btLine */,
    named[38] /* btPoly */,
    named[31] /* btRect */,
    named[30] /* btBox */,
    named[32] /* btArc */,
    named[33] /* btSector */,
    named[34] /* btChord */,
    named[37] /* btText */,
    decl( NULL, IupFill(), 
      "SIZE", "5", NULL ),
    named[40] /* btImage */,
    named[39] /* btImageRGB */,
    decl( NULL, IupFill(), 
      "SIZE", "5", NULL ),
    named[41] /* btClip */,
    decl( NULL, IupFill(), 
      "SIZE", "30", NULL ),
  NULL), 
    "GAP", "2", NULL );
  named[45] = decl( "cnvColorBar", IupCanvas( "cmdColorBarRepaint" ), 
    "BUTTON_CB", "cmdColorBarButtonCB", 
    "RESIZE_CB", "cmdColorBarResizeCB", 
    "SIZE", "220x12", 
    "BORDER", "NO", 
    "EXPAND", "NO", NULL );
  named[46] = decl( "cnvMain", IupCanvas( "cmdRepaint" ), 
    "MOTION_CB", "cmdMotionCB", 
    "BUTTON_CB", "cmdButtonCB", 
    "RESIZE_CB", "cmdResizeCB", NULL );
  named[47] = decl( "DeskTop", IupVbox(
    decl( NULL, IupFill(), 
      "SIZE", "5", NULL ),
    IupHbox(
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[44] /* PrimBar */,
      decl( NULL, IupFill(), 
        "SIZE", "2", NULL ),
      IupVbox(
        decl( NULL, IupFill(), 
          "SIZE", "2", NULL ),
        named[43] /* lbMousePos */,
        decl( NULL, IupFill(), 
          "SIZE", "5", NULL ),
        named[46] /* cnvMain */,
        decl( NULL, IupFill(), 
          "SIZE", "2", NULL ),
        named[45] /* cnvColorBar */,
        decl( NULL, IupFill(), 
          "SIZE", "5", NULL ),
        named[28] /* lbStatusLine */,
      NULL),
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
    NULL),
    decl( NULL, IupFill(), 
      "SIZE", "5", NULL ),
  NULL), NULL );
  named[48] = decl( "dlgMain", IupDialog(
    named[47] /* DeskTop */
  ), 
    "TITLE", "CD Test 5.3", 
    "MENU", "mnMain", 
    "ICON", "CdTestIcon", 
    "K_cZ", "cmdEditUndo", 
    "GETFOCUS_CB", "cmdGetFocusCB", 
    "KILLFOCUS_CB", "cmdKillFocusCB", 
    "CLOSE_CB", "cmdFileExit", NULL );
  named[49] = decl( "cnvWDCanvas", IupCanvas( "cmdWDRepaint" ), 
    "BORDER", "NO", NULL );
  named[50] = decl( "dlgWDCanvas", IupDialog(
    named[49] /* cnvWDCanvas */
  ), 
    "TITLE", "WD Canvas", 
    "CLISE_CB", "cmdCloseWD", 
    "SIZE", "200x200", 
    "PARENTDIALOG", "dlgMain", 
    "GAP", "5x5", NULL );
  named[51] = decl( "cnvPICCanvas", IupCanvas( "cmdPICRepaint" ), 
    "BORDER", "NO", NULL );
  named[52] = decl( "dlgPICCanvas", IupDialog(
    named[51] /* cnvPICCanvas */
  ), 
    "TITLE", "PIC Canvas", 
    "CLISE_CB", "cmdClosePIC", 
    "SIZE", "200x200", 
    "PARENTDIALOG", "dlgMain", 
    "GAP", "5x5", NULL );
  named[53] = decl( "btOptionsHide", IupButton( "Hide", "cmdOptionsHide" ), 
    "SIZE", "30", NULL );
  named[54] = decl( "tgSimulate", IupToggle( "Simulate", "cmdSimulate" ), 
    "VALUE", "OFF", 
    "SIZE", "55", NULL );
  named[55] = decl( "tgStretchPlay", IupToggle( "Stretch Play", "cmdStretchPlay" ), 
    "VALUE", "OFF", 
    "SIZE", "70", NULL );
  named[56] = decl( "tgNoBuffering", IupToggle( "No buffering", "cmdNoBuffering" ), 
    "VALUE", "ON", NULL );
  named[57] = decl( "tgImageBuffer", IupToggle( "CD_DBUFFER", "cmdImageBuffer" ), NULL );
  named[58] = decl( "tgRGBBuffer", IupToggle( "CD_DBUFFERRGB", "cmdRGBBuffer" ), NULL );
  named[59] = decl( "rdBuffering", IupRadio(
    IupVbox(
      named[56] /* tgNoBuffering */,
      named[57] /* tgImageBuffer */,
      named[58] /* tgRGBBuffer */,
    NULL)
  ), NULL );
  named[60] = decl( "OptionsDesktop", IupVbox(
    decl( NULL, IupVbox(
      decl( NULL, IupFrame(
        named[59] /* rdBuffering */
      ), 
        "TITLE", "Buffering:", 
        "MARGIN", "5x5", 
        "SIZE", "80", NULL ),
      decl( NULL, IupFill(), 
        "SIZE", "10", NULL ),
      named[54] /* tgSimulate */,
      named[55] /* tgStretchPlay */,
      decl( NULL, IupFill(), 
        "SIZE", "10", NULL ),
      named[53] /* btOptionsHide */,
      decl( NULL, IupFill(), 
        "SIZE", "2", NULL ),
    NULL), 
      "GAP", "2", NULL ),
  NULL), NULL );
  named[61] = decl( "dlgOptions", IupDialog(
    named[60] /* OptionsDesktop */
  ), 
    "TITLE", "Options", 
    "PARENTDIALOG", "dlgMain", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "MARGIN", "5x2", NULL );
  named[62] = decl( "lstTextAlignment", IupList( "cmdTextAlignment" ), 
    "1", "CD_NORTH", 
    "2", "CD_SOUTH", 
    "3", "CD_EAST", 
    "4", "CD_WEST", 
    "5", "CD_NORTH_EAST", 
    "6", "CD_NORTH_WEST", 
    "7", "CD_SOUTH_EAST", 
    "8", "CD_SOUTH_WEST", 
    "9", "CD_CENTER", 
    "10", "CD_BASE_LEFT", 
    "11", "CD_BASE_CENTER", 
    "12", "CD_BASE_RIGHT", 
    "DROPDOWN", "YES", 
    "VALUE", "10", 
    "SIZE", "89", NULL );
  named[63] = decl( "txtMarkSize", IupText( "cmdInteger" ), 
    "NC", "4", 
    "SIZE", "20x12", 
    "VALUE", "10", NULL );
  named[64] = decl( "lstMarkType", IupList( "cmdMarkType" ), 
    "1", "CD_PLUS", 
    "2", "CD_STAR", 
    "3", "CD_CIRCLE", 
    "4", "CD_X", 
    "5", "CD_BOX", 
    "6", "CD_DIAMOND", 
    "7", "CD_HOLLOW_CIRCLE", 
    "8", "CD_HOLLOW_BOX", 
    "9", "CD_HOLLOW_DIAMOND", 
    "DROPDOWN", "YES", 
    "VALUE", "2", 
    "SIZE", "80", NULL );
  named[65] = decl( "lstWriteMode", IupList( "cmdWriteMode" ), 
    "1", "CD_REPLACE", 
    "2", "CD_XOR", 
    "3", "CD_NOT_XOR", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[66] = decl( "lstFontTypeFace", IupList( "cmdFontTypeFace" ), 
    "1", "CD_SYSTEM", 
    "2", "CD_COURIER", 
    "3", "CD_TIMES_ROMAN", 
    "4", "CD_HELVETICA", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[67] = decl( "lstLineCap", IupList( "cmdLineCap" ), 
    "1", "CD_CAPFLAT", 
    "2", "CD_CAPSQUARE", 
    "3", "CD_CAPROUND", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[68] = decl( "lstLineJoin", IupList( "cmdLineJoin" ), 
    "1", "CD_BEVEL", 
    "2", "CD_MITER", 
    "3", "CD_ROUND", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[69] = decl( "lstFillMode", IupList( "cmdFillMode" ), 
    "1", "CD_EVENODD", 
    "2", "CD_WINDING", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[70] = decl( "lstFontStyle", IupList( "cmdFontStyle" ), 
    "1", "CD_PLAIN", 
    "2", "CD_BOLD", 
    "3", "CD_ITALIC", 
    "4", "CD_BOLD_ITALIC", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[71] = decl( "txtLineWidth", IupText( "cmdInteger" ), 
    "SIZE", "30", 
    "NC", "3", 
    "VALUE", "1", NULL );
  named[72] = decl( "txtFontSize", IupText( "cmdInteger" ), 
    "SIZE", "30", 
    "NC", "3", 
    "VALUE", "12", NULL );
  named[73] = decl( "txtTextOrientation", IupText( "cmdInteger" ), 
    "SIZE", "30", 
    "NC", "3", 
    "VALUE", "0", NULL );
  named[74] = decl( "lstLineStyle", IupList( "cmdLineStyle" ), 
    "1", "CD_CONTINUOUS", 
    "2", "CD_DASHED", 
    "3", "CD_DOTTED", 
    "4", "CD_DASH_DOT", 
    "5", "CD_DASH_DOT_DOT", 
    "6", "CD_CUSTOM", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", NULL );
  named[75] = decl( "tgSolid", IupToggle( "CD_SOLID", "cmdSolid" ), 
    "VALUE", "ON", NULL );
  named[76] = decl( "tgHatch", IupToggle( "CD_HATCH", "cmdHatch" ), NULL );
  named[77] = decl( "tgStipple", IupToggle( "CD_STIPPLE", "cmdStipple" ), NULL );
  named[78] = decl( "tgPattern", IupToggle( "CD_PATTERN", "cmdPattern" ), NULL );
  named[79] = decl( "lstOpacity", IupList( "cmdOpacity" ), 
    "1", "CD_OPAQUE", 
    "2", "CD_TRANSPARENT", 
    "VALUE", "2", 
    "DROPDOWN", "YES", 
    "SIZE", "80", 
    "ACTIVE", "YES", NULL );
  named[80] = decl( "lstHatchStyle", IupList( "cmdHatchStyle" ), 
    "1", "CD_HORIZONTAL", 
    "2", "CD_VERTICAL", 
    "3", "CD_FDIAGONAL", 
    "4", "CD_BDIAGONAL", 
    "5", "CD_CROSS", 
    "6", "CD_DIAGCROSS", 
    "VALUE", "1", 
    "DROPDOWN", "YES", 
    "SIZE", "80", 
    "ACTIVE", "YES", NULL );
  named[81] = decl( "btAttributesHide", IupButton( "Hide", "cmdAttributesHide" ), 
    "SIZE", "30", NULL );
  named[82] = decl( "rdInteriorStyle", IupRadio(
    IupVbox(
      named[75] /* tgSolid */,
      named[76] /* tgHatch */,
      named[77] /* tgStipple */,
      named[78] /* tgPattern */,
    NULL)
  ), NULL );
  named[83] = decl( "AttributesDesktop", IupVbox(
    IupHbox(
      decl( NULL, IupVbox(
        IupLabel( "Write Mode:" ),
        named[65] /* lstWriteMode */,
        decl( NULL, IupFill(), 
          "SIZE", "4", NULL ),
        decl( NULL, IupFrame(
          IupVbox(
            IupLabel( "Back Opacity:" ),
            named[79] /* lstOpacity */,
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Fill Mode:" ),
            named[69] /* lstFillMode */,
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            decl( NULL, IupFrame(
              named[82] /* rdInteriorStyle */
            ), 
              "TITLE", "Interior Style:", 
              "MARGIN", "5x5", 
              "SIZE", "80", NULL ),
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Hatch Style:" ),
            named[80] /* lstHatchStyle */,
          NULL)
        ), 
          "TITLE", "Fill Attributes", 
          "MARGIN", "5x5", NULL ),
        decl( NULL, IupFill(), 
          "SIZE", "10", NULL ),
        decl( NULL, IupFrame(
          IupVbox(
            IupLabel( "Mark Type:" ),
            named[64] /* lstMarkType */,
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Mark Size:" ),
            named[63] /* txtMarkSize */,
          NULL)
        ), 
          "TITLE", "Mark Attributes", 
          "MARGIN", "5x5", NULL ),
        decl( NULL, IupFill(), 
          "SIZE", "10", NULL ),
        named[81] /* btAttributesHide */,
      NULL), 
        "GAP", "2", NULL ),
      decl( NULL, IupVbox(
        decl( NULL, IupFrame(
          IupVbox(
            IupLabel( "Font Typeface:" ),
            named[66] /* lstFontTypeFace */,
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Font Style:" ),
            named[70] /* lstFontStyle */,
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Font Size:" ),
            named[72] /* txtFontSize */,
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            decl( NULL, IupLabel( "Text Alignment:" ), 
              "SIZE", "x9", NULL ),
            named[62] /* lstTextAlignment */,
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            decl( NULL, IupLabel( "Text Orientation:" ), 
              "SIZE", "x9", NULL ),
            named[73] /* txtTextOrientation */,
          NULL)
        ), 
          "TITLE", "Text Attributes", 
          "MARGIN", "5x5", NULL ),
        decl( NULL, IupFill(), 
          "SIZE", "10", NULL ),
        decl( NULL, IupFrame(
          IupVbox(
            IupLabel( "Line Style:" ),
            named[74] /* lstLineStyle */,
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Line Width:" ),
            named[71] /* txtLineWidth */,
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Line Cap:" ),
            named[67] /* lstLineCap */,
            decl( NULL, IupFill(), 
              "SIZE", "2", NULL ),
            IupLabel( "Line Join:" ),
            named[68] /* lstLineJoin */,
          NULL)
        ), 
          "TITLE", "Line Attributes", 
          "MARGIN", "5x5", NULL ),
      NULL), 
        "GAP", "2", NULL ),
    NULL),
  NULL), NULL );
  named[84] = decl( "dlgAttributes", IupDialog(
    named[83] /* AttributesDesktop */
  ), 
    "TITLE", "Attributes", 
    "PARENTDIALOG", "dlgMain", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdAttributesHide", 
    "MARGIN", "5x2", NULL );
  named[85] = decl( "txtLBX1", IupText( "cmdInteger" ), 
    "NC", "8", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[86] = decl( "txtLBX2", IupText( "cmdInteger" ), 
    "NC", "8", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[87] = decl( "txtLBY1", IupText( "cmdInteger" ), 
    "NC", "8", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[88] = decl( "txtLBY2", IupText( "cmdInteger" ), 
    "NC", "8", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[89] = decl( "btLBDraw", IupButton( "Draw", "cmdDraw" ), 
    "SIZE", "30", NULL );
  named[90] = decl( "btLBHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[91] = decl( "LBData", IupVbox(
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "X1:" ), 
        "SIZE", "15x9", NULL ),
      named[85] /* txtLBX1 */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Y1:" ), 
        "SIZE", "15x9", NULL ),
      named[87] /* txtLBY1 */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "X2:" ), 
        "SIZE", "15x9", NULL ),
      named[86] /* txtLBX2 */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Y2:" ), 
        "SIZE", "15x9", NULL ),
      named[88] /* txtLBY2 */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[92] = decl( "LBDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[91] /* LBData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[89] /* btLBDraw */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[90] /* btLBHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[93] = decl( "dlgLB", IupDialog(
    named[92] /* LBDeskTop */
  ), 
    "TITLE", "Line Parameters", 
    "PARENTDIALOG", "dlgMain", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "MARGIN", "5x5", NULL );
  named[94] = decl( "txtASXC", IupText( "cmdInteger" ), 
    "NC", "4", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[95] = decl( "txtASYC", IupText( "cmdInteger" ), 
    "NC", "4", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[96] = decl( "txtASW", IupText( "cmdInteger" ), 
    "NC", "4", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[97] = decl( "txtASH", IupText( "cmdInteger" ), 
    "NC", "4", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[98] = decl( "txtASAngle1", IupText( "cmdReal" ), 
    "NC", "10", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[99] = decl( "txtASAngle2", IupText( "cmdReal" ), 
    "NC", "10", 
    "SIZE", "30x12", 
    "VALUE", "360", NULL );
  named[100] = decl( "btASDraw", IupButton( "Draw", "cmdDraw" ), 
    "SIZE", "30", NULL );
  named[101] = decl( "btASHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[102] = decl( "ASData", IupVbox(
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "Xc:" ), 
        "SIZE", "30x9", NULL ),
      named[94] /* txtASXC */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Yc:" ), 
        "SIZE", "30x9", NULL ),
      named[95] /* txtASYC */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "W:" ), 
        "SIZE", "30x9", NULL ),
      named[96] /* txtASW */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "H:" ), 
        "SIZE", "30x9", NULL ),
      named[97] /* txtASH */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "Angle1:" ), 
        "SIZE", "30x9", NULL ),
      named[98] /* txtASAngle1 */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Angle2:" ), 
        "SIZE", "30x9", NULL ),
      named[99] /* txtASAngle2 */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[103] = decl( "ASDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[102] /* ASData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[100] /* btASDraw */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[101] /* btASHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[104] = decl( "dlgAS", IupDialog(
    named[103] /* ASDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Arc Parameters", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "MARGIN", "5x5", NULL );
  named[105] = decl( "txtPixelX", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[106] = decl( "txtPixelY", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[107] = decl( "btPixelDraw", IupButton( "Draw", "cmdDraw" ), 
    "SIZE", "30", NULL );
  named[108] = decl( "btPixelHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[109] = decl( "PixelData", IupVbox(
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "X:" ), 
        "SIZE", "10x9", NULL ),
      named[105] /* txtPixelX */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Y:" ), 
        "SIZE", "10x9", NULL ),
      named[106] /* txtPixelY */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[110] = decl( "PixelDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[109] /* PixelData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[107] /* btPixelDraw */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[108] /* btPixelHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[111] = decl( "dlgPixel", IupDialog(
    named[110] /* PixelDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Pixel Parameters", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "MARGIN", "5x5", NULL );
  named[112] = decl( "txtMarkX", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[113] = decl( "txtMarkY", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[114] = decl( "btMarkDraw", IupButton( "Draw", "cmdDraw" ), 
    "SIZE", "30", NULL );
  named[115] = decl( "btMarkHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[116] = decl( "MarkData", IupVbox(
    decl( NULL, IupHbox(
      IupFill(),
      decl( NULL, IupLabel( "X:" ), 
        "SIZE", "10x9", NULL ),
      named[112] /* txtMarkX */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Y:" ), 
        "SIZE", "10x9", NULL ),
      named[113] /* txtMarkY */,
      IupFill(),
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[117] = decl( "MarkDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[116] /* MarkData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[114] /* btMarkDraw */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[115] /* btMarkHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[118] = decl( "dlgMark", IupDialog(
    named[117] /* MarkDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Mark Parameters", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "MARGIN", "5x5", NULL );
  named[119] = decl( "txtTextX", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[120] = decl( "txtTextY", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[121] = decl( "txtTextS", IupText( "cmdString" ), 
    "NC", "100", 
    "SIZE", "89x12", 
    "VALUE", "Text", NULL );
  named[122] = decl( "btTextDraw", IupButton( "Draw", "cmdDraw" ), 
    "SIZE", "30", NULL );
  named[123] = decl( "btTextHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[124] = decl( "TextData", IupVbox(
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "X:" ), 
        "SIZE", "10x9", NULL ),
      named[119] /* txtTextX */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Y:" ), 
        "SIZE", "10x9", NULL ),
      named[120] /* txtTextY */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    IupHbox(
      IupVbox(
        decl( NULL, IupLabel( "Text:" ), 
          "SIZE", "25x9", NULL ),
        named[121] /* txtTextS */,
      NULL),
    NULL),
  NULL), NULL );
  named[125] = decl( "TextDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[124] /* TextData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[122] /* btTextDraw */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[123] /* btTextHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[126] = decl( "dlgText", IupDialog(
    named[125] /* TextDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Text Parameters", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "RESIZE", "NO", 
    "MARGIN", "5x5", NULL );
  named[127] = decl( "tgOpenLines", IupToggle( "CD_OPEN_LINES", "cmdOpenLines" ), 
    "VALUE", "ON", NULL );
  named[128] = decl( "tgClosedLines", IupToggle( "CD_CLOSED_LINES", "cmdClosedLines" ), NULL );
  named[129] = decl( "tgFilled", IupToggle( "CD_FILL", "cmdFill" ), NULL );
  named[130] = decl( "tgClip", IupToggle( "CD_CLIP", "cmdPolyClip" ), NULL );
  named[131] = decl( "tgBezier", IupToggle( "CD_BEZIER", "cmdPolyBezier" ), NULL );
  named[132] = decl( "btPolyHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[133] = decl( "rdMode", IupRadio(
    IupVbox(
      named[127] /* tgOpenLines */,
      named[128] /* tgClosedLines */,
      named[129] /* tgFilled */,
      named[130] /* tgClip */,
      named[131] /* tgBezier */,
    NULL)
  ), NULL );
  named[134] = decl( "PolyDesktop", IupVbox(
    decl( NULL, IupFill(), 
      "SIZE", "5", NULL ),
    IupHbox(
      IupFill(),
      decl( NULL, IupFrame(
        IupHbox(
          decl( NULL, IupFill(), 
            "SIZE", "5", NULL ),
          named[133] /* rdMode */,
        NULL)
      ), 
        "TITLE", "Polygon Mode:", NULL ),
      IupFill(),
    NULL),
    decl( NULL, IupFill(), 
      "SIZE", "10", NULL ),
    IupHbox(
      IupFill(),
      named[132] /* btPolyHide */,
      IupFill(),
    NULL),
    decl( NULL, IupFill(), 
      "SIZE", "5", NULL ),
  NULL), NULL );
  named[135] = decl( "dlgPoly", IupDialog(
    named[134] /* PolyDesktop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Polygon Parameters", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "CLOSE_CB", "cmdMsgHide", NULL );
  named[136] = decl( "txtClipXmin", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[137] = decl( "txtClipXmax", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[138] = decl( "txtClipYmin", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[139] = decl( "txtClipYmax", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[140] = decl( "btClipOff", IupButton( "Off", "cmdClipOff" ), 
    "SIZE", "30", NULL );
  named[141] = decl( "btClipArea", IupButton( "Area", "cmdClipArea" ), 
    "SIZE", "30", NULL );
  named[142] = decl( "btClipPoly", IupButton( "Polygon", "cmdClipPoly" ), 
    "SIZE", "50", NULL );
  named[143] = decl( "btClipHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[144] = decl( "ClipData", IupVbox(
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "Xmin:" ), 
        "SIZE", "25x9", NULL ),
      named[136] /* txtClipXmin */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Ymin:" ), 
        "SIZE", "25x9", NULL ),
      named[138] /* txtClipYmin */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "Xmax:" ), 
        "SIZE", "25x9", NULL ),
      named[137] /* txtClipXmax */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Ymax:" ), 
        "SIZE", "25x9", NULL ),
      named[139] /* txtClipYmax */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[145] = decl( "ClipDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[144] /* ClipData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[140] /* btClipOff */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[141] /* btClipArea */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[142] /* btClipPoly */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[143] /* btClipHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[146] = decl( "dlgClip", IupDialog(
    named[145] /* ClipDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Clipping", 
    "MAXBOX", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "MINBOX", "NO", 
    "RESIZE", "NO", 
    "MARGIN", "5x5", NULL );
  named[147] = decl( "txtImageX", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[148] = decl( "txtImageY", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[149] = decl( "txtImageW", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[150] = decl( "txtImageH", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[151] = decl( "btImagePut", IupButton( "Put", "cmdImagePut" ), 
    "SIZE", "30", NULL );
  named[152] = decl( "btImageGet", IupButton( "Get", "cmdImageGet" ), 
    "SIZE", "30", NULL );
  named[153] = decl( "btImageHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[154] = decl( "ImageData", IupVbox(
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "X:" ), 
        "SIZE", "30x9", NULL ),
      named[147] /* txtImageX */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Y:" ), 
        "SIZE", "30x9", NULL ),
      named[148] /* txtImageY */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "Width:" ), 
        "SIZE", "30x9", NULL ),
      named[149] /* txtImageW */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Height:" ), 
        "SIZE", "30x9", NULL ),
      named[150] /* txtImageH */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[155] = decl( "ImageDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[154] /* ImageData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[152] /* btImageGet */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[151] /* btImagePut */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[153] /* btImageHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[156] = decl( "dlgImage", IupDialog(
    named[155] /* ImageDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "Server Image", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "RESIZE", "NO", 
    "MARGIN", "5x5", NULL );
  named[157] = decl( "txtImageRGBX", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[158] = decl( "txtImageRGBY", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[159] = decl( "txtImageRGBW", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[160] = decl( "txtImageRGBH", IupText( "cmdInteger" ), 
    "NC", "5", 
    "SIZE", "30x12", 
    "VALUE", "0", NULL );
  named[161] = decl( "btImageRGBPut", IupButton( "Put", "cmdImageRGBPut" ), 
    "SIZE", "30", NULL );
  named[162] = decl( "btImageRGBGet", IupButton( "Get", "cmdImageRGBGet" ), 
    "SIZE", "30", NULL );
  named[163] = decl( "btImageRGBHide", IupButton( "Hide", "cmdMsgHide" ), 
    "SIZE", "30", NULL );
  named[164] = decl( "ImageRGBData", IupVbox(
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "X:" ), 
        "SIZE", "30x9", NULL ),
      named[157] /* txtImageRGBX */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Y:" ), 
        "SIZE", "30x9", NULL ),
      named[158] /* txtImageRGBY */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    decl( NULL, IupHbox(
      decl( NULL, IupLabel( "Width:" ), 
        "SIZE", "30x9", NULL ),
      named[159] /* txtImageRGBW */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      decl( NULL, IupLabel( "Height:" ), 
        "SIZE", "30x9", NULL ),
      named[160] /* txtImageRGBH */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
  NULL), NULL );
  named[165] = decl( "ImageRGBDeskTop", IupVbox(
    IupHbox(
      IupFill(),
      named[164] /* ImageRGBData */,
      IupFill(),
    NULL),
    IupHbox(
      IupFill(),
      named[162] /* btImageRGBGet */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[161] /* btImageRGBPut */,
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      named[163] /* btImageRGBHide */,
      IupFill(),
    NULL),
  NULL), NULL );
  named[166] = decl( "dlgImageRGB", IupDialog(
    named[165] /* ImageRGBDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "RGB Image", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "CLOSE_CB", "cmdMsgHide", 
    "RESIZE", "NO", 
    "MARGIN", "5x5", NULL );
  named[167] = decl( "btCDTest", IupButton( "Close", "cmdCloseAbout" ), NULL );
  named[168] = decl( "AboutDeskTop", IupHbox(
    IupFill(),
    decl( NULL, IupVbox(
      IupLabel( "CD Test 5.3" ),
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupLabel( "Antonio Scuri" ),
      IupLabel( "Diego Nehab" ),
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupLabel( "Tecgraf/PUC-Rio" ),
      decl( NULL, IupFill(), 
        "SIZE", "5", NULL ),
      IupLabel( "CD Library Version" ),
      named[169] = decl( "lblVersion", IupLabel( "" ), NULL ),
      named[167] /* btCDTest */,
    NULL), 
      "ALIGNMENT", "ACENTER", NULL ),
    IupFill(),
  NULL), 
    "MARGIN", "5x5", 
    "GAP", "2", NULL );
  named[170] = decl( "dlgHelpAbout", IupDialog(
    named[168] /* AboutDeskTop */
  ), 
    "PARENTDIALOG", "dlgMain", 
    "TITLE", "About", 
    "MAXBOX", "NO", 
    "MINBOX", "NO", 
    "RESIZE", "NO", NULL );
}
