
.PHONY: do_all cd_freetype cd cdx11 cdgdk cd_pdflib cdpdf cdgl cdcontextplus cdcairo cdlua3 cdluapdf3 cdluagl3 cdlua5 cdluapdf5 cdluagl5 cdluacontextplus5 cdluacairo5 cdluaim5
do_all: cd_freetype cd cd_pdflib cdpdf cdgl cdlua5 cdluapdf5 cdluagl5 cdluaim5

cd_freetype:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cd_freetype
cd:
	@$(MAKE) --no-print-directory -f tecmake.mak
cdx11:
	@$(MAKE) --no-print-directory -f tecmake.mak USE_X11=Yes
cdgdk:
	@$(MAKE) --no-print-directory -f tecmake.mak USE_GDK=Yes
cd_pdflib:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cd_pdflib
cdpdf:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdpdf
cdgl:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdgl
cdcontextplus:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdcontextplus
cdcairo:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdcairo
cdlua3:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdlua3
cdluapdf3:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdluapdf3
cdluagl3:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdluagl3
cdlua5:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdlua5
cdluapdf5:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdluapdf5
cdluagl5:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdluagl5
cdluacontextplus5:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdluacontextplus5
cdluacairo5:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdluacairo5
cdluaim5:
	@$(MAKE) --no-print-directory -f tecmake.mak MF=cdluaim5
